pipeline {
    agent any
    stages {
        stage('Build User Service') {
            steps {
                dir('user-service') {
                    echo "Building User Service..."
                    sh 'docker build -t user-service:latest .'
                }
            }
        }
        stage('Deploy User Service') {
            steps {
                echo "Deploying User Service..."
                // Example: run docker container
                sh 'docker run -d --name user-service -p 5000:5000 user-service:latest'
            }
        }
    }
}